server:
  port: 6667
lsj:
  grpc:
    discovery:
      enabled: true
      name: ${spring.application.name}
      nacos:
        enabled: true
        host: 43.136.117.137:8848
        namespace: 0713fa77-f644-4937-a6a6-0b444d39eff6
      etcd:
        enabled: true
        host: http://127.0.0.1:2379
    port: 9094
spring:
  application:
    name: core-grpc-server-test
