server:
  port: 7777
lsj:
  grpc:
    discovery:
      nacos:
        host: 43.136.117.137:8848
        namespace: 0713fa77-f644-4937-a6a6-0b444d39eff6
spring:
  application:
    name: core-grpc-client-test
