server:
  port: 7777
lsj:
  grpc:
    discovery:
      discovery-type: ETCD
      nacos:
        host: 43.136.117.137:8848
        namespace: 0713fa77-f644-4937-a6a6-0b444d39eff6
      etcd:
        host: http://127.0.0.1:2379
        namespace: dev

spring:
  application:
    name: core-grpc-client-test
